### ISSUE TITLE
Question(not an issue): Reliability of A9 and A9G

### ISSUE THREAD

**Issue by garudaonekh** [marcosasilvalepe/GPS#3]
hi,
Can you share your exprience on this module? I love its feature(2g gprs+gps+soc) and super cheap price but I doubt its stability for deploying to iOT projects. I need it for Farm iot projects.

Thanks

**Comment by marcosasilvalepe** [comment]
I found it very reliable. I wish there was a 3g version of the module but this one works well enough. 

For GPS I recommend getting a separate antenna and placing it somewhere it can get a clear view of the sky.

The great advantages are the size of the module, you can use micropython to program it (with a few minor bugs) and how powerful it is.

**Comment by garudaonekh** [comment]
How long have you used it? My personal experience is three months. I target its service life of 2 years

Yes, Micropython is cool but several bugs. My SMS reading is not reliable(time out very often especially  when there are many sms). MQTT connection is down ad never recover even If I try many time which I have to reset the device every two days.

**Comment by marcosasilvalepe** [comment]
For SMS I read the message, process it and immediately delete it. I don't store them because sims don't have that much space.

I haven't used MQTT. I use the module mainly as a gps tracker for vehicles and to transmit the data using http post requests. The server does the rest and transmits relevant data to the module.

It's pretty reliable using post requests but I had to always use try statements so that the module doesn't get halted if it encounters an error. If you don't wrap your code in try statements then whenever an error happens the module just stops and it won't work again until you reboot it.

**Comment by garudaonekh** [comment]
For how long have you used this module?

**Comment by marcosasilvalepe** [comment]
More than a year
